export const NEWS_DATA = "NEWS_DATA";
export const DATA_PENDING = "DATA_PENDING";
export const WEATHER_DATA = "WEATHER_DATA";
export const WEATHER_DATA_IZMIR = "WETHER_DATA_IZMIR";
export const DATA_REJECTED = "DATA_REJECTED";
export const CURRENCY_DATA = "CURRENCY_DATA";